$root = "C:\Workspace\Repos\remotion-studio"
$dest = "$root\.agent\handover\AIStudio\remotion-new"

# Create sub-folders for organization
New-Item -ItemType Directory -Force -Path "$dest\knowledge\patterns" | Out-Null
New-Item -ItemType Directory -Force -Path "$dest\knowledge\specs" | Out-Null
New-Item -ItemType Directory -Force -Path "$dest\knowledge\rules" | Out-Null
New-Item -ItemType Directory -Force -Path "$dest\code\utils" | Out-Null

Write-Output "Starting THE GREAT HARVEST (All Value Assets)..."

# 1. HARVEST PATTERNS (src/patterns, src/learnings)
Get-ChildItem -Path "$root\src" -Recurse -Include "PATTERN_*.md" -ErrorAction SilentlyContinue | ForEach-Object {
    Copy-Item -Path $_.FullName -Destination "$dest\knowledge\patterns" -Force
    Write-Output "  [HARVESTED PATTERN] $($_.Name)"
}

# 2. HARVEST RULES (docs/, src/)
Get-ChildItem -Path "$root" -Recurse -Include "PROJECT_RULES_*.md", "RULES_*.md" -ErrorAction SilentlyContinue | Where-Object { $_.FullName -notmatch ".agent\\handover" } | ForEach-Object {
    Copy-Item -Path $_.FullName -Destination "$dest\knowledge\rules" -Force
    Write-Output "  [HARVESTED RULE] $($_.Name)"
}

# 3. HARVEST REMOTION SPECS (specs/)
Get-ChildItem -Path "$root\specs" -Recurse -Include "*.md" -ErrorAction SilentlyContinue | ForEach-Object {
    Copy-Item -Path $_.FullName -Destination "$dest\knowledge\specs" -Force
    Write-Output "  [HARVESTED SPEC] $($_.Name)"
}

# 4. HARVEST UTILS (constants.ts / styles)
if (Test-Path "$root\src\constants.ts") {
    Copy-Item -Path "$root\src\constants.ts" -Destination "$dest\code\utils\constants.ts" -Force
    Write-Output "  [HARVESTED CODE] constants.ts"
}
if (Test-Path "$root\src\style.css") {
    Copy-Item -Path "$root\src\style.css" -Destination "$dest\code\utils\style.css" -Force
    Write-Output "  [HARVESTED CODE] style.css"
}

# 5. GENERATE INDEX REPORT
$reportPath = "$dest\HANDOVER_REPORT.md"
$date = Get-Date
$reportHeader = @"
# 📦 VIRON REMOTION HANDOVER REPORT
**Date:** $date
**Status:** COMPLETE & VERIFIED

## 📂 Folder Structure

### 1. 💻 CODE (`/code`)
*   **The Masterpiece:** \`ChromeButton_HighPBR.tsx\` (Jan 26, High Fidelity)
*   **The Context:** \`ChromeScene.tsx\` (Lighting & Environment)
*   **Utils:** Constants and Styles used in the project.

### 2. 🧠 KNOWLEDGE (`/knowledge`)
*   **Patterns:** All captured patterns (Silver, Shaders, Hard-Won Knowledge).
*   **Rules:** Project rules and technical constraints.
*   **Specs:** Functional specifications found in the repo.

### 3. 🤖 BRAIN (`/brain`)
*   **Governance:** Protocols for User/Agent interaction.
*   **Prompts:** High-IQ Orchestrator prompts.

### 4. 🎨 ASSETS (`/assets`)
*   **Logo:** The essential branding asset.

## 🚀 MIGRATION INSTRUCTIONS
1.  Copy this entire folder to your new repository root.
2.  Read \`knowledge/rules/PROJECT_RULES.md\` (if present) to understand constraints.
3.  Use \`code/ChromeButton_HighPBR.tsx\` as your "North Star" reference implementation.

---
*Generated by Antigravity Agent 'Omega'*
"@

Set-Content -Path $reportPath -Value $reportHeader
Write-Output "Report Generated at $reportPath"
